import bcrypt from 'bcryptjs';
const data = {
  users: [
    {
      name: 'James',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Shoe Shirt',
      slug: 'shoe-shirt',
      category: 'Shoes',
      image: '/images/shirt1.jpg',
      price: 70,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Fits Shoes',
      slug: 'fits-shoes',
      category: 'Shoes',
      image: '/images/shirt2.jpg',
      price: 80,
      brand: 'Adidas',
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Slim Shirt',
      slug: 'slim-shirt',
      category: 'Shoes',
      image: '/images/shirt3.jpg',
      price: 90,
      brand: 'Raymond',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Golf Shoes',
      slug: 'golf-shoes',
      category: 'Shoes',
      image: '/images/pants1.jpg',
      price: 90,
      brand: 'Oliver',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'Smart looking Shoe',
    },
    {
      name: 'Fit Shoes',
      slug: 'fit-shoes',
      category: 'Shoes',
      image: '/images/pants2.jpg',
      price: 95,
      brand: 'Zara',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoe',
    },
    {
      name: 'Classic Shoes',
      slug: 'classic-shoes',
      category: 'Shoes',
      image: '/images/pants3.jpg',
      price: 75,
      brand: 'Casely',
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: 'A popular Shoe',
    },
  ],
};
export default data;
